# Training on Hypersim
# @package _global_
defaults:
  - viewseg_hypersim_base


experiment_name: 'viewseg_hypersim_source_4'
data:
  image_size: [768, 1024] # [height, width]
  render_size: [768, 1024]
train:
  batch_size: 1
  num_views: 4